Style/Documentation:
  Enabled: false

Style/LineLength:
  Max: 164

Style/MethodLength:
  Max: 31

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
