Metrics/LineLength:
  Max: 164

Metrics/MethodLength:
  Max: 31

Metrics/AbcSize:
  Max: 46

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

Style/MultilineOperationIndentation:
  Enabled: false
